### ISSUE TITLE
Closing window

### ISSUE THREAD

**Issue by Juris3D** [Jordonbc/UE4_SimpleWindows#4]
Sorry if that's simple, but I don't know how to close opened Advanced Text window from some BP node? Meaning, timeout is "0" (to stay forever), and i don't want to close it with mouse click. Thank You.

**Comment by Jordonbc** [comment]
It turns out that "Display Advanced Text" doesn't output a window manager reference so I added one. closing the window can be accessed by dragging out the referenced window manager and running the close window function from it.
![issue](https://user-images.githubusercontent.com/16258926/54025698-3b283700-4193-11e9-811f-9752fc2842cf.jpg)
